CXX := g++
CXX_WARN := -Wall -Wextra

quick:
	$(CXX) $(CXX_WARN) quicksort.cpp -o quicksort.out

dpqs:
	$(CXX) $(CXX_WARN) dpqs.cpp -o dpqs.out

squick:
	$(CXX) $(CXX_WARN) selectquick.cpp -o selectquick.out

sdpqs:
	$(CXX) $(CXX_WARN) selectdpqs.cpp -o selectdpqs.out

clean:
	rm -f *.out